{% set version="1.24.0" %}
{% set name="Vega" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: f348fc3d9ce497bf022cdf8f4836ad22a27fa90e70772126f45d1cde4eb0626c
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.10'
  run:
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/Vega.html
  license: GPL-2
  summary: 'Vega (Variational Estimator for Genomic Aberrations) is an algorithm that
    adapts a very popular variational model (Mumford and Shah) used in image segmentation
    so that chromosomal aberrant regions can be efficiently detected.'
