{% set version="1.22.0" %}
{% set name="cqn" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a92299abeb3282896301b55f70196064f23e7eb9c1b437296ff20c951773110c
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-preprocesscore
    - 'r-base >=2.10.0'
    - r-mclust
    - r-nor1mix
    - r-quantreg
  run:
    - bioconductor-preprocesscore
    - 'r-base >=2.10.0'
    - r-mclust
    - r-nor1mix
    - r-quantreg
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/cqn.html
  license: Artistic-2.0
  summary: 'A normalization tool for RNA-Seq data, implementing the conditional quantile
    normalization method.'
