{% set version="1.36.0" %}
{% set name="occugene" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 50ca7b2f59125b1fbb7aa8d8f9b1bca4fa832dfdeac78d3de852a83d933e5420
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.0.0'
  run:
    - 'r-base >=2.0.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/occugene.html
  license: 'GPL (>= 2)'
  summary: 'Statistical tools for building random mutagenesis libraries for prokaryotes.
    The package has functions for handling the occupancy distribution for a multinomial
    and for estimating the number of essential genes in random transposon mutagenesis
    libraries.'
