{% set version="2.4.0" %}
{% set name="rols" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ad6471f1b85ac7c32277eeac72b397ef40dd64300befade620cb24ac5e9b3363
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
  run:
    - bioconductor-biobase
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/rols.html
  license: GPL-2
  summary: 'An interface to the Ontology Lookup Service (OLS) to access and query
    hundred of ontolgies directly from R.'
