{% set version="1.16.0" %}
{% set name="RSVSim" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 98a733020abb8cca9aa02e94d6a652c633720dbafac299e7dcc8a57fd214dce0
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-shortread
    - 'r-base >=3.0.0'
  run:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-shortread
    - 'r-base >=3.0.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/RSVSim.html
  license: LGPL-3
  summary: 'RSVSim is a package for the simulation of deletions, insertions, inversion,
    tandem-duplications and translocations of various sizes in any genome available
    as FASTA-file or BSgenome data package. SV breakpoints can be placed uniformly
    accross the whole genome, with a bias towards repeat regions and regions of high
    homology (for hg19) or at user-supplied coordinates.'
