{% set version="1.12.0" %}
{% set name="AtlasRDF" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 09a3d0c5c2309414af6177bcaa925b2c8fd3f9c5e07b29eb87954f6980780b71
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.10'
    - r-hash
    - r-sparql
  run:
    - 'r-base >=2.10'
    - r-hash
    - r-sparql
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/AtlasRDF.html
  license: 'Apache License 2.0'
  summary: 'Query the Gene Expression Atlas RDF data at the European Bioinformatics
    Institute using genes, experimental factors (such as disease, cell type, compound
    treatments), pathways and proteins. Also contains a function to perform an enrichment
    of your gene list across Experimental Factor Ontology (EFO) using the Atlas background
    set.'
