{% set version="1.4.0" %}
{% set name="MethPed" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a15f7a52affe798e2fb895019ba93f9e4e67d48be4c72c57ee32790418639371
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'r-base >=3.0.0'
    - r-randomforest
  run:
    - bioconductor-biobase
    - 'r-base >=3.0.0'
    - r-randomforest
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/MethPed.html
  license: GPL-2
  summary: 'Classification of pediatric tumors into biologically defined subtypes
    is challenging and multifaceted approaches are needed. For this aim, we developed
    a diagnostic classifier based on DNA methylation profiles. We offer MethPed as
    an easy-to-use toolbox that allows researchers and clinical diagnosticians to
    test single samples as well as large cohorts for subclass prediction of pediatric
    brain tumors.  The current version of MethPed can classify the following tumor
    diagnoses/subgroups: Diffuse Intrinsic Pontine Glioma (DIPG), Ependymoma, Embryonal
    tumors with multilayered rosettes (ETMR), Glioblastoma (GBM), Medulloblastoma
    (MB) - Group 3 (MB_Gr3), Group 4 (MB_Gr3), Group WNT (MB_WNT), Group SHH (MB_SHH)
    and Pilocytic Astrocytoma (PiloAstro).'
