{% set version="1.52.0" %}
{% set name="affycomp" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5779b634bcb8d12078bf1540e66579cbcf4a55cd8f14731838e8eb6960080d33
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.3.3'
    - 'r-base >=2.13.0'
  run:
    - 'bioconductor-biobase >=2.3.3'
    - 'r-base >=2.13.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/affycomp.html
  license: 'GPL (>= 2)'
  summary: 'The package contains functions that can be used to compare expression
    measures for Affymetrix Oligonucleotide Arrays.'
