{% set version="1.14.0" %}
{% set name="Roleswitch" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8ebb1a63fe73819fa5ab0339ce156d2797cbe9f8b4ad26e1bbbece9a4dc07b42
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-microrna
    - 'r-base >=2.10'
    - r-dbi
    - r-plotrix
    - r-pracma
    - r-reshape
  run:
    - bioconductor-biobase
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-microrna
    - 'r-base >=2.10'
    - r-dbi
    - r-plotrix
    - r-pracma
    - r-reshape
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/Roleswitch.html
  license: GPL-2
  summary: 'Infer Probabilities of MiRNA-mRNA Interaction Signature (ProMISe) using
    paired expression data from a single sample. Roleswitch operates in two phases
    by inferring the probability of mRNA (miRNA) being the targets ("targets") of
    miRNA (mRNA), taking into account the expression of all of the mRNAs (miRNAs)
    due to their potential competition for the same miRNA (mRNA). Due to dynamic miRNA
    repression in the cell, Roleswitch assumes that the total transcribed mRNA levels
    are higher than the observed (equilibrium) mRNA levels and iteratively updates
    the total transcription of each mRNA targets based on the above inference. NB:
    in the paper, we used ProMISe as both the model name and inferred score name.'
