{% set version="1.46.0" %}
{% set name="plier" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 31af674383c43559610903fdef49daac06f54f5f815e90fc34a09740d92df437
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-biobase
    - 'r-base >=2.0'
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - 'r-base >=2.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/plier.html
  license: 'GPL (>= 2)'
  summary: 'The PLIER (Probe Logarithmic Error Intensity Estimate) method produces
    an improved signal by accounting for experimentally observed patterns in probe
    behavior and handling error at the appropriately at low and high signal values.'
