{% set version="1.42.0" %}
{% set name="weaver" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 295bb2a1de9dd8cad808fd47d7da9f064f36dd2e85615b64aada1901e81c5a3b
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.5.0'
    - r-codetools
    - r-digest
  run:
    - 'r-base >=2.5.0'
    - r-codetools
    - r-digest
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/weaver.html
  license: GPL-2
  summary: 'This package provides enhancements on the Sweave() function in the base
    package.  In particular a facility for caching code chunk results is included.'
