{% set version="1.52.0" %}
{% set name="prada" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 205fce198d2de3d617138a67c4e73e884cc3f57661383eaa7fe14236b7e8d3f1
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'r-base >=2.10'
    - r-mass
    - r-rcolorbrewer
    - r-rrcov
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - 'r-base >=2.10'
    - r-mass
    - r-rcolorbrewer
    - r-rrcov
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/prada.html
  license: LGPL
  summary: 'Tools for analysing and navigating data from high-throughput phenotyping
    experiments based on cellular assays and fluorescent detection (flow cytometry
    (FACS), high-content screening microscopy).'
