{% set version="1.4.2" %}
{% set name="globalSeq" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: b52a22310fafa63b48e13d14df78d9ea7af4ac7bd1d761e035b086e108f4b30f
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=3.0.0'
  run:
    - 'r-base >=3.0.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/globalSeq.html
  license: GPL-3
  summary: 'The method may be conceptualised as a test of overall significance in
    regression analysis, where the response variable is overdispersed and the number
    of explanatory variables exceeds the sample size.'
