{% set version="1.4.0" %}
{% set name="nucleoSim" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5a1f4e93a53e6df297346ac6888d27c575241f171dba73f41fb0d90e00995417
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
  run:
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/nucleoSim.html
  license: Artistic-2.0
  summary: 'This package can generate a synthetic map with reads covering the nucleosome
    regions as well as a synthetic map with forward and reverse reads emulating next-generation
    sequencing. The user has choice between three different distributions for the
    read positioning: Normal, Student and Uniform.'
