{% set version="1.6.1" %}
{% set name="SWATH2stats" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2c59fe08f2ebd68fa9c6e444005203824ffef9899c16daf4df86abf0725dbc5a
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.10.0'
    - r-data.table
    - r-ggplot2
    - r-reshape2
  run:
    - 'r-base >=2.10.0'
    - r-data.table
    - r-ggplot2
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SWATH2stats.html
  license: GPL-3
  summary: 'This package is intended to transform SWATH data from the OpenSWATH software
    into a format readable by other statistics packages while performing filtering,
    annotation and FDR estimation.'
