{% set version="1.26.0" %}
{% set name="Mulcom" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e81763677a8e3fcbcca1e90ce9a6b8694d84efa7f0c391fff173c0e7734eeb04
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'r-base >=2.10'
    - r-fields
  run:
    - bioconductor-biobase
    - 'r-base >=2.10'
    - r-fields
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/Mulcom.html
  license: GPL-2
  summary: 'Identification of differentially expressed genes and false discovery rate
    (FDR) calculation by Multiple Comparison test'
