{% set version="1.10.0" %}
{% set name="flowDensity" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 0a0cc0a9cb135594fa93a1149d8becc6d3d9bb567f509443e4ec65aa3edea6cf
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-flowcore
    - 'r-base >=2.10.0'
    - r-car
    - r-geomap
    - r-gplots
    - r-rfoc
  run:
    - bioconductor-flowcore
    - 'r-base >=2.10.0'
    - r-car
    - r-geomap
    - r-gplots
    - r-rfoc
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/flowDensity.html
  license: Artistic-2.0
  summary: 'This package provides tools for automated sequential gating analogous
    to the manual gating strategy based on the density of the data.'
