{% set version="1.32.0" %}
{% set name="RPA" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: db7e318985195943272d4b202ee9219353b956bca6aa52127c8bd2f20ded0d3a
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-biocgenerics
    - bioconductor-phyloseq
    - 'r-base >=3.1.1'
  run:
    - bioconductor-affy
    - bioconductor-biocgenerics
    - bioconductor-phyloseq
    - 'r-base >=3.1.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/RPA.html
  license: 'BSD_2_clause + file LICENSE'
  summary: 'Probabilistic analysis of probe reliability and differential gene expression
    on short oligonucleotide arrays. Lahti et al. "Probabilistic Analysis of Probe
    Reliability in Differential Gene Expression Studies with Short Oligonucleotide
    Arrays", TCBB/IEEE, 2011. http://doi.ieeecomputersociety.org/10.1109/TCBB.2009.38'
