{% set version="1.18.0" %}
{% set name="CancerMutationAnalysis" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2ba8eb60addc2923fafaf9b53115e82d4b70ac5a175322e5f77675c0dec2380b
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - bioconductor-limma
    - bioconductor-qvalue
    - 'r-base >=2.10.0'
  run:
    - bioconductor-annotationdbi
    - bioconductor-limma
    - bioconductor-qvalue
    - 'r-base >=2.10.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/CancerMutationAnalysis.html
  license: 'GPL (>= 2) + file LICENSE'
  summary: 'This package implements gene and gene-set level analysis methods for somatic
    mutation studies of cancer.  The gene-level methods distinguish between driver
    genes (which play an active role in tumorigenesis) and passenger genes (which
    are mutated in tumor samples, but have no role in tumorigenesis) and incorporate
    a two-stage study design.  The gene-set methods implement a patient-oriented approach,
    which calculates gene-set scores for each sample, then combines them across samples;
    a gene-oriented approach which uses the Wilcoxon test is also provided for comparison.'
