{% set version="1.4.0" %}
{% set name="MultiDataSet" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e9b592478f1a949b17e20db2fe27356e3ed66aac648a002973790ae6c3e3d2e6
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - 'r-base >=3.3'
  run:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - 'r-base >=3.3'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/MultiDataSet.html
  license: 'file LICENSE'
  summary: 'Implementation of the BRGE''s (Bioinformatic Research Group in Epidemiology
    from Center for Research in Environmental Epidemiology) MultiDataSet and MethylationSet.
    MultiDataSet is designed for integrating multi omics data sets and MethylationSet
    to contain normalized methylation data. These package contains base classes for
    MEAL and rexposome packages.'
