{% set version="1.12.0" %}
{% set name="MPFE" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 4f216013b2d27581dcfda68278cbae14b2c7b4771e8b2179401968a320a3d66f
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
  run:
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/MPFE.html
  license: 'GPL (>= 3)'
  summary: 'Estimate distribution of methylation patterns from a table of counts from
    a bisulphite sequencing experiment given a non-conversion rate and read error
    rate.'
