{% set version="1.30.0" %}
{% set name="DEGseq" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 3d09f6accd78f3375ad1533bdcb8d9cd38ce0a69949aff3810763a4853f63f3a
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-qvalue
    - 'r-base >=2.8.0'
    - r-samr
  run:
    - bioconductor-qvalue
    - 'r-base >=2.8.0'
    - r-samr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/DEGseq.html
  license: 'LGPL (>=2)'
  summary: 'DEGseq is an R package to identify differentially expressed genes from
    RNA-Seq data.'
