{% set version="1.14.0" %}
{% set name="curatedOvarianData" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/data/experiment/src/contrib/{{ name }}_{{
      version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8dc206562e089a036dff55d3b8b0d0a50e64bf14bde578251f843317a96a5a05
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-biocgenerics
    - 'r-base >=2.10.0'
  run:
    - bioconductor-affy
    - bioconductor-biocgenerics
    - 'r-base >=2.10.0'
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/data/experiment/html/curatedOvarianData.html
  license: Artistic-2.0
  summary: 'The curatedOvarianData package provides data for gene expression analysis
    in patients with ovarian cancer.'
