{% set version="1.12.0" %}
{% set name="PECA" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 6b34e644a3983b8cafe6936c863fc9ea1107b827aa59a27f758ece9bcd1fc59a
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-genefilter
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-rots
    - r-aroma.affymetrix
    - r-aroma.core
    - 'r-base >=3.3'
  run:
    - bioconductor-affy
    - bioconductor-genefilter
    - bioconductor-limma
    - bioconductor-preprocesscore
    - bioconductor-rots
    - r-aroma.affymetrix
    - r-aroma.core
    - 'r-base >=3.3'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/PECA.html
  license: 'GPL (>= 2)'
  summary: 'Calculates Probe-level Expression Change Averages (PECA) to identify differential
    expression in Affymetrix gene expression microarray studies or in proteomic studies
    using peptide-level mesurements respectively.'
