{% set version="1.34.0" %}
{% set name="xmapbridge" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: b3dc44d09a5fce6cde58384d0027000dde60a40437757c09b55a0890522e9a10
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.0'
  run:
    - 'r-base >=2.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/xmapbridge.html
  license: LGPL-3
  summary: 'xmapBridge can plot graphs in the X:Map genome browser. This package exports
    plotting files in a suitable format.'
