{% set version="2.40.0" %}
{% set name="nnNorm" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: bfbaf8c99ad5545597dc062d240b988d4547387f0c05015eb40d1683c56adb23
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-marray
    - 'r-base >=2.2.0'
    - r-nnet
  run:
    - bioconductor-marray
    - 'r-base >=2.2.0'
    - r-nnet
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/nnNorm.html
  license: LGPL
  summary: 'This package allows to detect and correct for spatial and intensity biases
    with two-channel microarray data. The normalization method implemented in this
    package is based on robust neural networks fitting.'
