{% set version="1.50.0" %}
{% set name="affypdnn" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5760b21e4b0a630b8a7babe289adf85f8862345d1ec7e36eedf6c2658934733d
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-affy >=1.5'
    - 'r-base >=2.13.0'
  run:
    - 'bioconductor-affy >=1.5'
    - 'r-base >=2.13.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/affypdnn.html
  license: LGPL
  summary: 'The package contains functions to perform the PDNN method described by
    Li Zhang et al.'
