{% set version="1.2.0" %}
{% set name="SNPediaR" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2d3dabbb7851b67a86fecf321583291ff5fe9a59904c33ccfd05a6a01778a9bb
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=3.0.0'
    - r-jsonlite
    - r-rcurl
  run:
    - 'r-base >=3.0.0'
    - r-jsonlite
    - r-rcurl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SNPediaR.html
  license: GPL-2
  summary: 'SNPediaR provides some tools for downloading and parsing data from the
    SNPedia web site <http://www.snpedia.com>. The implemented functions allow users
    to import the wiki text available in SNPedia pages and to extract the most relevant
    information out of them. If some information in the downloaded pages is not automatically
    processed by the library functions, users can easily implement their own parsers
    to access it in an efficient way.'
