{% set version="1.10.0" %}
{% set name="riboSeqR" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 78e63d244331e150693c8b157a9d27d4d60bd0d1a5fb7ef71f8e370aff4da229
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-bayseq
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-seqlogo
    - r-abind
    - 'r-base >=3.0.2'
  run:
    - bioconductor-bayseq
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rsamtools
    - bioconductor-seqlogo
    - r-abind
    - 'r-base >=3.0.2'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/riboSeqR.html
  license: GPL-3
  summary: 'Plotting functions, frameshift detection and parsing of sequencing data
    from ribosome profiling experiments.'
