{% set version="1.16.0" %}
{% set name="SPEM" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ddf358f874243225bd8fbf9095e0bc1704db516a01ccf6c27af03fe59096a320
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'r-base >=2.15.1'
    - r-rsolnp
  run:
    - bioconductor-biobase
    - 'r-base >=2.15.1'
    - r-rsolnp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SPEM.html
  license: GPL-2
  summary: 'This package can optimize the parameter in S-system models given time
    series data'
