{% set version="1.14.0" %}
{% set name="rTRM" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 90769def5f125c3248eed4bf7795c900c4ab6efaa5e85d750efd66644450b511
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - 'r-base >=2.10'
    - r-dbi
    - 'r-igraph >=1.0'
    - r-rsqlite
  run:
    - bioconductor-annotationdbi
    - 'r-base >=2.10'
    - r-dbi
    - 'r-igraph >=1.0'
    - r-rsqlite
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/rTRM.html
  license: GPL-3
  summary: 'rTRM identifies transcriptional regulatory modules (TRMs) from protein-protein
    interaction networks.'
