{% set version="2.34.0" %}
{% set name="rbsurv" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ee1739ab64524eb1c59f6340aa30c36bc0676e7b5313768b5a515913f5ba86cc
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.5.5'
    - 'r-base >=2.5.0'
    - r-survival
  run:
    - 'bioconductor-biobase >=2.5.5'
    - 'r-base >=2.5.0'
    - r-survival
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/rbsurv.html
  license: 'GPL (>= 2)'
  summary: 'This package selects genes associated with survival.'
