{% set version="1.8.0" %}
{% set name="ALDEx2" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 04c2bb73c634c3b274937dc3e7268efac9f08a93b8f0e091c7b5babeacd53610
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
  run:
    - bioconductor-biocparallel
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/ALDEx2.html
  license: 'file LICENSE'
  summary: 'A differential abundance analysis for the comparison of two or more conditions.
    For example, single-organism and meta-RNA-seq high-throughput sequencing assays,
    or of selected and unselected values from in-vitro sequence selections. Uses a
    Dirichlet-multinomial model to infer abundance from counts, that has been optimized
    for three or more experimental replicates. Infers sampling variation and calculates
    the expected false discovery rate given the biological and sampling variation
    using the Wilcox rank test or Welches t-test (aldex.ttest) or the glm and Kruskal
    Wallis tests (aldex.glm). Reports both P and fdr values calculated by the Benjamini
    Hochberg correction.'
