{% set version="1.18.0" %}
{% set name="MiRaGE" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: caa5cd7431a1ff90ff9ec48486fb472d5a1393de0e981da5d7f6a402612a94ad
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.23.3'
    - bioconductor-biocgenerics
    - bioconductor-s4vectors
    - 'r-base >=3.1.0'
  run:
    - bioconductor-annotationdbi
    - 'bioconductor-biobase >=2.23.3'
    - bioconductor-biocgenerics
    - bioconductor-s4vectors
    - 'r-base >=3.1.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/MiRaGE.html
  license: GPL
  summary: 'The package contains functions for inferece of target gene regulation
    by miRNA, based on only target gene expression profile.'
