{% set version="1.16.0" %}
{% set name="RRHO" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: f64d458da28ab97830d0562d092ad82a79c39a98fdeaf997febfc3089e3dd802
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.10'
    - r-venndiagram
  run:
    - 'r-base >=2.10'
    - r-venndiagram
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/RRHO.html
  license: GPL-2
  summary: 'The package is aimed at inference on the amount of agreement in two sorted
    lists using the Rank-Rank Hypergeometric Overlap test.'
