{% set version="1.34.0" %}
{% set name="tspair" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5a509bbb46d8494f40eaabf8780fe6dd8b0546d40d4f330478f3c26ef7e35ba3
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.4.0'
    - 'r-base >=2.10'
  run:
    - 'bioconductor-biobase >=2.4.0'
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/tspair.html
  license: GPL-2
  summary: 'These functions calculate the pair of genes that show the maximum difference
    in ranking between two user specified groups. This "top scoring pair" maximizes
    the average of sensitivity and specificity over all rank based classifiers using
    a pair of genes in the data set. The advantage of classifying samples based on
    only the relative rank of a pair of genes is (a) the classifiers are much simpler
    and often more interpretable than more complicated classification schemes and
    (b) if arrays can be classified using only a pair of genes, PCR based tests could
    be used for classification of samples. See the references for the tspcalc() function
    for references regarding TSP classifiers.'
