{% set version="1.4.0" %}
{% set name="DNAshapeR" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 946ee0f468f94b4776c74b013b88c3f75091415378f84aebc4864cd569e46e9e
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - 'r-base >=3.3'
    - r-fields
    - 'r-rcpp >=0.12.1'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biostrings
    - bioconductor-genomicranges
    - 'r-base >=3.3'
    - r-fields
    - 'r-rcpp >=0.12.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/DNAshapeR.html
  license: GPL-2
  summary: 'DNAhapeR is an R/BioConductor package for ultra-fast, high-throughput
    predictions of DNA shape features. The package allows to predict, visualize and
    encode DNA shape features for statistical learning.'
