{% set version="1.14.0" %}
{% set name="OmicCircos" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2bb4b8a62db0d288cf4944c8a1bd66fda6d193a0806927a92288ec6c13c0c2da
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-genomicranges
    - 'r-base >=2.14.0'
  run:
    - bioconductor-genomicranges
    - 'r-base >=2.14.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/OmicCircos.html
  license: GPL-2
  summary: 'OmicCircos is an R application and package for generating high-quality
    circular plots for omics data.'
