{% set version="1.44.0" %}
{% set name="RbcBook1" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 4f463039ca4d0d89549da7f56431d20029e3a5de0234a1c6c6990f1fbb76328e
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-graph
    - 'r-base >=2.10'
    - r-rpart
  run:
    - bioconductor-biobase
    - bioconductor-graph
    - 'r-base >=2.10'
    - r-rpart
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/RbcBook1.html
  license: Artistic-2.0
  summary: 'tools for building book'
