{% set version="3.16.0" %}
{% set name="safe" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 0f894abe9d87f0d9a90bf2fd36f20c26d6f1cc2a3a4313fc17f5192e8ccc1a91
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'r-base >=2.4.0'
    - r-sparsem
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'r-base >=2.4.0'
    - r-sparsem
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/safe.html
  license: 'GPL (>= 2)'
  summary: 'SAFE is a resampling-based method for testing functional categories in
    gene expression experiments. SAFE can be applied to 2-sample and multi-class comparisons,
    or simple linear regressions. Other experimental designs can also be accommodated
    through user-defined functions.'
