{% set version="1.8.0" %}
{% set name="RBM" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 63020faaada6f85e8d4ca69200e5d303412ccdb33a9da533740b454573b42987
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - bioconductor-marray
    - 'r-base >=3.2.0'
  run:
    - bioconductor-limma
    - bioconductor-marray
    - 'r-base >=3.2.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/RBM.html
  license: 'GPL (>= 2)'
  summary: 'Use A Resampling-Based Empirical Bayes Approach to Assess Differential
    Expression in Two-Color Microarrays and RNA-Seq data sets.'
