{% set version="1.38.0" %}
{% set name="mdqc" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: b1e1b75e31d55ce3ae896f61ea35b5a76e883ed8cceec9e47f590fbdbaebc882
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.2.1'
    - r-cluster
    - r-mass
  run:
    - 'r-base >=2.2.1'
    - r-cluster
    - r-mass
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/mdqc.html
  license: 'LGPL (>= 2)'
  summary: 'MDQC is a multivariate quality assessment method for microarrays based
    on quality control (QC) reports. The Mahalanobis distance of an array''s quality
    attributes is used to measure the similarity of the quality of that array against
    the quality of the other arrays. Then, arrays with unusually high distances can
    be flagged as potentially low-quality.'
