{% set version="1.6.0" %}
{% set name="myvariant" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 568e7c67901e914f21f98f1c0f15bdcef37ba7a4bf373eaf2502d4e9680299b5
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-genomeinfodb
    - bioconductor-s4vectors
    - bioconductor-variantannotation
    - 'r-base >=3.2.1'
    - r-hmisc
    - r-httr
    - r-jsonlite
    - r-magrittr
    - r-plyr
  run:
    - bioconductor-genomeinfodb
    - bioconductor-s4vectors
    - bioconductor-variantannotation
    - 'r-base >=3.2.1'
    - r-hmisc
    - r-httr
    - r-jsonlite
    - r-magrittr
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/myvariant.html
  license: Artistic-2.0
  summary: 'MyVariant.info is a comprehensive aggregation of variant annotation resources.
    myvariant is a wrapper for querying MyVariant.info services'
