{% set version="1.8.0" %}
{% set name="PROPER" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 695fa6c23186bee4640253ee66e3f800d9f4584a6a96dca09ef7f896882b2b27
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-edger
    - 'r-base >=2.10'
  run:
    - bioconductor-edger
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/PROPER.html
  license: GPL
  summary: 'This package provide simulation based methods for evaluating the statistical
    power in differential expression analysis from RNA-seq data.'
