{% set version="3.2.3" %}
{% set name="KEGG.db" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/data/annotation/src/contrib/{{ name }}_{{
      version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 02ea4630a3ec06a8d9a6151627c96d3f71dfc7e8857800bb5c0cdb6a838d6963
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=1.34.3'
    - 'r-base >=2.7.0'
  run:
    - 'bioconductor-annotationdbi >=1.34.3'
    - 'r-base >=2.7.0'
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/data/annotation/html/KEGG.db.html
  license: 'file LICENSE'
  summary: 'A set of annotation maps for KEGG assembled using data from KEGG'
