{% set version="2.16.0" %}
{% set name="SSPA" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 3f4d8a9018b71cdbb96ae230da6c6ce95d57edea0a384bf9aea0da1cb27f72a2
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - bioconductor-qvalue
    - 'r-base >=2.12'
    - r-lattice
  run:
    - bioconductor-limma
    - bioconductor-qvalue
    - 'r-base >=2.12'
    - r-lattice
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SSPA.html
  license: 'GPL (>= 2)'
  summary: 'General Sample size and power analysis for microarray and next-generation
    sequencing data.'
