{% set version="1.42.0" %}
{% set name="AffyExpress" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 97eca5d88e1bc32a5c1d69a2f382120eae0ee0ee6efe9be8821abc89c3f4ccdc
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-affy >=1.23.4'
    - bioconductor-limma
    - 'r-base >=2.10'
  run:
    - 'bioconductor-affy >=1.23.4'
    - bioconductor-limma
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/AffyExpress.html
  license: LGPL
  summary: 'The purpose of this package is to provide a comprehensive and easy-to-use
    tool for quality assessment and to identify differentially expressed genes in
    the Affymetrix gene expression data.'
