{% set version="4.18.2" %}
{% set name="EBImage" %}
{% set bioc="3.5" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ebeb07981e945289a49096e2c1d2c399d6f24b47604b8555504dd26f1ff3ba13
build:
  number: 0

  # previous recipe skipped OSX
  # skip: True # [osx]
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biocgenerics >=0.7.1'
    - r-abind
    - r-base
    - 'r-fftwtools >=0.9_7'
    - r-jpeg
    - r-locfit
    - r-png
    - r-tiff
  run:
    - 'bioconductor-biocgenerics >=0.7.1'
    - r-abind
    - r-base
    - 'r-fftwtools >=0.9_7'
    - r-jpeg
    - r-locfit
    - r-png
    - r-tiff
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL
  summary: 'EBImage provides general purpose functionality for image processing and analysis. In the context of (high-throughput) microscopy-based cellular assays, EBImage offers tools to segment cells and extract quantitative cellular descriptors. This allows the automation of such tasks using the R programming language and facilitates the use of other tools in the R environment for signal processing, statistical modeling, machine learning and visualization with image data.'
