{% set version="1.34.0" %}
{% set name="BicARE" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5bddf37087e373c3549df775fd85d2fac165fcc272b7effabae3cd331b9196ba
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-gseabase
    - bioconductor-multtest
    - 'r-base >=1.8.0'
  run:
    - 'bioconductor-biobase >=2.5.5'
    - bioconductor-gseabase
    - bioconductor-multtest
    - 'r-base >=1.8.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/BicARE.html
  license: GPL-2
  summary: 'Biclustering Analysis and Results Exploration'
