{% set version="1.48.0" %}
{% set name="splicegear" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: f7bbd63689cc148cee7cd9f4848db8ade98103c37b909ed8808f06e2c70bbb8b
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotate
    - 'bioconductor-biobase >=2.5.5'
    - 'r-base >=2.6.0'
    - r-xml
  run:
    - bioconductor-annotate
    - 'bioconductor-biobase >=2.5.5'
    - 'r-base >=2.6.0'
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/splicegear.html
  license: LGPL
  summary: 'A set of tools to work with alternative splicing'
