{% set version="1.36.0" %}
{% set name="BGmix" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8173838cf907cadcaecf1c8cebd8307367f0c1b92e4c340ed252ab1326c5b85b
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.3.1'
    - r-kernsmooth
  run:
    - 'r-base >=2.3.1'
    - r-kernsmooth
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/BGmix.html
  license: GPL-2
  summary: 'Fully Bayesian mixture models for differential gene expression'
