{% set version="1.16.1" %}
{% set name="omicade4" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2b20ceaf83598fe711b7bedcea01b4b6b1e1b44214d98dcef3a5b2bbe332ee4e
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-made4
    - r-ade4
    - 'r-base >=3.0.0'
  run:
    - bioconductor-made4
    - r-ade4
    - 'r-base >=3.0.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/omicade4.html
  license: GPL-2
  summary: 'Multiple co-inertia analysis of omics datasets'
