{% set version="1.34.0" %}
{% set name="metahdep" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 262f984d0189b56274350987666fbb36419530b123ff3f9bf02948b0dbe96df1
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.10'
  run:
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/metahdep.html
  license: GPL-3
  summary: 'Tools for meta-analysis in the presence of hierarchical (and/or sampling)
    dependence, including with gene expression studies'
