{% set version="1.6.0" %}
{% set name="rnaseqcomp" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 0781ae5a5bcd18037cd84b3c88729261bf53f3439507da814b1312200ff554b8
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=3.2.0'
    - r-rcolorbrewer
  run:
    - 'r-base >=3.2.0'
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/rnaseqcomp.html
  license: GPL-3
  summary: 'Several quantitative and visualized benchmarks for RNA-seq quantification
    pipelines. Two-condition quantifications for genes, transcripts, junctions or
    exons by each pipeline with necessary meta information should be organized into
    numeric matrices in order to proceed the evaluation.'
