{% set version="1.42.0" %}
{% set name="CALIB" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 9ecb78158e9256cf24fa21d5c8c637eeaaeecd41d75e632bc1e665c5fd147a3c
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-limma
    - 'r-base >=2.10'
  run:
    - bioconductor-limma
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/CALIB.html
  license: LGPL
  summary: 'This package contains functions for normalizing spotted microarray data,
    based on a physically motivated calibration model. The model parameters and error
    distributions are estimated from external control spikes.'
