{% set version="1.8.0" %}
{% set name="BEclear" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: def5676dcff0068c94627413150c32ca08c9e7656369d0172457ffc6251b9ad6
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-matrix
    - r-snowfall
  run:
    - r-base
    - r-matrix
    - r-snowfall
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/BEclear.html
  license: GPL-2
  summary: 'Provides some functions to detect and correct for batch effects in DNA
    methylation data. The core function "BEclear" is based on latent factor models
    and can also be used to predict missing values in any other matrix containing
    real numbers.'
