{% set version="1.10.0" %}
{% set name="CFAssay" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 508bccfcc5b758faecb8bc64ec31a96e9b51010fda4e42eaf827ef4884c9b8fb
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.10.0'
  run:
    - 'r-base >=2.10.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/CFAssay.html
  license: LGPL
  summary: 'The package provides functions for calculation of linear-quadratic cell
    survival curves and for ANOVA of experimental 2-way designs along with the colony
    formation assay.'
