{% set version="1.10.0" %}
{% set name="Rnits" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: bffd37e4f74ff62ef7b992d23e0bacd5f5b360e55a06de78b0f9400963cc994e
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-qvalue
    - 'r-base >=3.1.0'
    - r-boot
    - r-ggplot2
    - r-reshape2
  run:
    - bioconductor-affy
    - bioconductor-biobase
    - bioconductor-impute
    - bioconductor-limma
    - bioconductor-qvalue
    - 'r-base >=3.1.0'
    - r-boot
    - r-ggplot2
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/Rnits.html
  license: GPL-3
  summary: 'R/Bioconductor package for normalization, curve registration and inference
    in time course gene expression data'
