{% set version="1.46.0" %}
{% set name="panp" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: d593cb75d2d1af9bdcd7fc3f4550db0928d6cf1b9fba19e204a970c3271a1468
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-affy >=1.23.4'
    - 'bioconductor-biobase >=2.5.5'
    - 'r-base >=2.10'
  run:
    - 'bioconductor-affy >=1.23.4'
    - 'bioconductor-biobase >=2.5.5'
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/panp.html
  license: 'GPL (>= 2)'
  summary: 'A function to make gene presence/absence calls based on distance from
    negative strand matching probesets (NSMP) which are derived from Affymetrix annotation.
    PANP is applied after gene expression values are created, and therefore can be
    used after any preprocessing method such as MAS5 or GCRMA, or PM-only methods
    like RMA. NSMP sets have been established for the HGU133A and HGU133-Plus-2.0
    chipsets to date.'
