{% set version="1.26.0" %}
{% set name="AnnotationFuncs" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 839736e03a3effb0e5c96bf5614f8400afc72f4aca6f470eb593c01f65ee5969
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - 'r-base >=2.7.0'
    - r-dbi
  run:
    - bioconductor-annotationdbi
    - 'r-base >=2.7.0'
    - r-dbi
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/AnnotationFuncs.html
  license: GPL-2
  summary: 'Functions for handling translating between different identifieres using
    the Biocore Data Team data-packages (e.g. org.Bt.eg.db).'
