{% set version="2.9" %}
{% set name="DO.db" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/data/annotation/src/contrib/{{ name }}_{{
      version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 762bcb9b5188274fd81d82f785cf2846a5acc61fad55e2ff8ec1502282c27881
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=1.9.7'
    - 'r-base >=2.7.0'
  run:
    - 'bioconductor-annotationdbi >=1.9.7'
    - 'r-base >=2.7.0'
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/data/annotation/html/DO.db.html
  license: Artistic-2.0
  summary: 'A set of annotation maps describing the entire Disease Ontology assembled
    using data from DO'
