{% set version="1.12.0" %}
{% set name="sangerseqR" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 17d8369b809bcb556ee77674f7741427f5cc132d54847fb640cfefb11773a768
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biostrings
    - 'r-base >=3.0.2'
    - r-shiny
  run:
    - bioconductor-biostrings
    - 'r-base >=3.0.2'
    - r-shiny
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/sangerseqR.html
  license: GPL-2
  summary: 'This package contains several tools for analyzing Sanger Sequencing data
    files in R, including reading .scf and .ab1 files, making basecalls and plotting
    chromatograms.'
