{% set version="1.4.0" %}
{% set name="metaCCA" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8565125494fc5140d94681e3415618223756deb84be91de38290cfdd2538ef8b
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
  run:
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/metaCCA.html
  license: 'MIT + file LICENSE'
  summary: 'metaCCA performs multivariate analysis of a single or multiple GWAS based
    on univariate regression coefficients. It allows multivariate representation of
    both phenotype and genotype. metaCCA extends the statistical technique of canonical
    correlation analysis to the setting where original individual-level records are
    not available, and employs a covariance shrinkage algorithm to achieve robustness.'
