{% set version="1.2.0" %}
{% set name="SPLINTER" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: d5dae9263342125d1e811732997fbf547ba6904ae08c5b60a070eac400ede5b1
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome.mmusculus.ucsc.mm9
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-seqlogo
    - 'r-base >=3.3.0'
    - r-ggplot2
    - r-plyr
  run:
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome.mmusculus.ucsc.mm9
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-gviz
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-seqlogo
    - 'r-base >=3.3.0'
    - r-ggplot2
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SPLINTER.html
  license: GPL-2
  summary: 'SPLINTER provides tools to analyze alternative splicing sites, interpret
    outcomes based on sequence information, select and design primers for site validiation
    and give visual representation of the event to guide downstream experiments.'
