{% set version="1.26.0" %}
{% set name="OTUbase" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ae7b5b1fabaf41b21b46cd247992804913613d7e4a14cde987a0877b251db73b
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-s4vectors
    - 'bioconductor-shortread >=1.23.15'
    - 'r-base >=2.9.0'
    - r-vegan
  run:
    - bioconductor-biobase
    - bioconductor-biostrings
    - bioconductor-iranges
    - bioconductor-s4vectors
    - 'bioconductor-shortread >=1.23.15'
    - 'r-base >=2.9.0'
    - r-vegan
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/OTUbase.html
  license: Artistic-2.0
  summary: 'Provides a platform for Operational Taxonomic Unit based analysis'
