{% set version="1.22.0" %}
{% set name="tweeDEseq" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2808424dcc6a3ec863a3698d0288c25877c1157559a8d0a92eeba0a67cc5e581
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-cqn
    - bioconductor-edger
    - bioconductor-limma
    - 'r-base >=2.12.0'
    - r-mass
  run:
    - bioconductor-cqn
    - bioconductor-edger
    - bioconductor-limma
    - 'r-base >=2.12.0'
    - r-mass
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/tweeDEseq.html
  license: 'GPL (>= 2)'
  summary: 'Differential expression analysis of RNA-seq using the Poisson-Tweedie
    family of distributions.'
