{% set version="1.40.0" %}
{% set name="flowViz" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 19b9d5c4abe932ac2c5e0e18a9bb250c926854919b85f1a1baa1b420b5df31ca
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'bioconductor-flowcore >=1.41.9'
    - 'r-base >=2.7.0'
    - r-hexbin
    - r-idpmisc
    - r-kernsmooth
    - r-lattice
    - r-latticeextra
    - r-mass
    - r-rcolorbrewer
  run:
    - bioconductor-biobase
    - 'bioconductor-flowcore >=1.41.9'
    - 'r-base >=2.7.0'
    - r-hexbin
    - r-idpmisc
    - r-kernsmooth
    - r-lattice
    - r-latticeextra
    - r-mass
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/flowViz.html
  license: Artistic-2.0
  summary: 'Provides visualization tools for flow cytometry data.'
