{% set version="1.22.0" %}
{% set name="RTopper" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 47df59b49aef38a0df46a019a7d9eda8dc3e204bd436d5d3319dfd221516fc73
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-limma
    - bioconductor-multtest
    - 'r-base >=2.11.0'
  run:
    - bioconductor-biobase
    - bioconductor-limma
    - bioconductor-multtest
    - 'r-base >=2.11.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/RTopper.html
  license: 'GPL (>= 3)'
  summary: 'the RTopper package is designed to perform and integrate gene set enrichment
    results across multiple genomic platforms.'
