{% set version="1.7.0" %}
{% set name="MeSHSim" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: bbdb064e9ed495790436242aa31137a89201d26fb6b2611bb882f09500d9eaab
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=3.0.0'
    - r-rcurl
    - r-xml
  run:
    - 'r-base >=3.0.0'
    - r-rcurl
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/MeSHSim.html
  license: GPL-2
  summary: 'Provide for measuring semantic similarity over MeSH headings and MEDLINE
    documents'
