{% set version="1.48.0" %}
{% set name="annaffy" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 3f305047abb0c5fc841905993e4fd11889985d4952238b18c10c097a3acfb352
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=0.1.15'
    - bioconductor-biobase
    - bioconductor-go.db
    - bioconductor-kegg.db
    - 'r-base >=2.5.0'
    - r-dbi
  run:
    - 'bioconductor-annotationdbi >=0.1.15'
    - bioconductor-biobase
    - bioconductor-go.db
    - bioconductor-kegg.db
    - 'r-base >=2.5.0'
    - r-dbi
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/annaffy.html
  license: LGPL
  summary: 'Functions for handling data from Bioconductor Affymetrix annotation data
    packages. Produces compact HTML and text reports including experimental data and
    URL links to many online databases. Allows searching biological metadata using
    various criteria.'
