{% set version="1.40.0" %}
{% set name="ConsensusClusterPlus" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 8ee5b67bef8cc46c74753cfcf7cbbc09260f019cc84bf7fcab2e42482f8e66e1
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-all
    - bioconductor-biobase
    - r-base
    - r-cluster
  run:
    - bioconductor-all
    - bioconductor-biobase
    - r-base
    - r-cluster
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/ConsensusClusterPlus.html
  license: 'GPL version 2'
  summary: 'algorithm for determining cluster count and membership by stability evidence
    in unsupervised analysis'
