{% set version="1.16.0" %}
{% set name="metaSeq" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ca2124d64559281f4919a1cd0c4ac2cc02fd90980a2c5790751e17152ed02d77
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-noiseq
    - 'r-base >=2.13.0'
    - r-rcpp
    - r-snow
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-noiseq
    - 'r-base >=2.13.0'
    - r-rcpp
    - r-snow
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/metaSeq.html
  license: Artistic-2.0
  summary: 'The probabilities by one-sided NOISeq are combined by Fisher''s method
    or Stouffer''s method'
