{% set version="2.22.0" %}
{% set name="gaga" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 6ca98eaafa8ba1570fd1791ef693471cc031b8bde1badc5e91aeba16786b3392
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-ebarrays
    - 'r-base >=2.8.0'
    - r-coda
    - r-mgcv
  run:
    - bioconductor-biobase
    - bioconductor-ebarrays
    - 'r-base >=2.8.0'
    - r-coda
    - r-mgcv
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/gaga.html
  license: 'GPL (>= 2)'
  summary: 'Implements the GaGa model for high-throughput data analysis, including
    differential expression analysis, supervised gene clustering and classification.
    Additionally, it performs sequential sample size calculations using the GaGa and
    LNNGV models (the latter from EBarrays package).'
