{% set version="1.22.0" %}
{% set name="CellNOptR" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e0d6cfbb58b4e2dbf82b9e260edace7aa40da23e55ea279169fb15d6274b5e04
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - 'r-base >=2.15.0'
    - r-ggplot2
    - r-hash
    - r-rcurl
    - r-xml
  run:
    - bioconductor-graph
    - bioconductor-rbgl
    - bioconductor-rgraphviz
    - 'r-base >=2.15.0'
    - r-ggplot2
    - r-hash
    - r-rcurl
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/CellNOptR.html
  license: GPL-3
  summary: 'This package does optimisation of boolean logic networks of signalling
    pathways based on a previous knowledge network and a set of data upon perturbation
    of the nodes in the network.'
