{% set version="1.38.0" %}
{% set name="bgafun" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a2911b0e1b4cde6d3cc96b2ac49fe0ffdaabea21108bb078fb6bce912e63636a
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-made4
    - r-ade4
    - r-base
    - r-seqinr
  run:
    - bioconductor-made4
    - r-ade4
    - r-base
    - r-seqinr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/bgafun.html
  license: Artistic-2.0
  summary: 'A method to identify specifity determining residues in protein families
    using Between Group Analysis'
