{% set version="1.10.0" %}
{% set name="rain" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: e9ad087eddce4c400df6f82908dcbe741393e125b0109ea4b356692567a7168e
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-multtest
    - 'r-base >=2.10'
    - r-gmp
  run:
    - bioconductor-multtest
    - 'r-base >=2.10'
    - r-gmp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/rain.html
  license: GPL-2
  summary: 'This package uses non-parametric methods to detect rhythms in time series.
    It deals with outliers, missing values and is optimized for time series comprising
    10-100 measurements. As it does not assume expect any distinct waveform it is
    optimal or detecting oscillating behavior (e.g. circadian or cell cycle) in e.g.
    genome- or proteome-wide biological measurements such as: micro arrays, proteome
    mass spectrometry, or metabolome measurements.'
