{% set version="1.34.0" %}
{% set name="parody" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 527322997f8836fd22d5d2c122157526c9fee868c56365fd436a2e648d4a3a13
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.5.0'
  run:
    - 'r-base >=2.5.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/parody.html
  license: Artistic-2.0
  summary: 'routines for univariate and multivariate outlier detection with a focus
    on parametric methods, but support for some methods based on resistant statistics'
