{% set version="1.16.0" %}
{% set name="PathNet" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 9846f9333e55c55eb9c772d06051e0a52ad2dbb698b66e5f0a2c3cba9808288f
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=1.14.0'
  run:
    - 'r-base >=1.14.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/PathNet.html
  license: GPL-3
  summary: 'PathNet uses topological information present in pathways and differential
    expression levels of genes (obtained from microarray experiment) to identify pathways
    that are 1) significantly enriched and 2) associated with each other in the context
    of differential expression. The algorithm is described in: PathNet: A tool for
    pathway analysis using topological information. Dutta B, Wallqvist A, and Reifman
    J. Source Code for Biology and Medicine 2012 Sep 24;7(1):10.'
