{% set version="1.24.0" %}
{% set name="MLP" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2d914e135c53c3851f85372d8e23b3354817458efda96b33288024adf404f2a7
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-affy
    - bioconductor-annotationdbi
    - r-base
    - r-gdata
    - r-gmodels
    - r-gplots
    - r-gtools
    - r-plotrix
  run:
    - bioconductor-affy
    - bioconductor-annotationdbi
    - r-base
    - r-gdata
    - r-gmodels
    - r-gplots
    - r-gtools
    - r-plotrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/MLP.html
  license: GPL-3
  summary: 'Mean Log P Analysis'
