{% set version="2.40.0" %}
{% set name="EBarrays" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: dae3cf9851aa7eca709dd5a5fa99b1dccdaab5c0f246ad91c0bbbaf60d9014c9
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'r-base >=1.8.0'
    - r-cluster
    - r-lattice
  run:
    - bioconductor-biobase
    - 'r-base >=1.8.0'
    - r-cluster
    - r-lattice
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/EBarrays.html
  license: 'GPL (>= 2)'
  summary: 'EBarrays provides tools for the analysis of replicated/unreplicated microarray
    data.'
