{% set version="1.26.0" %}
{% set name="SQUADD" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 23919630292585dd0965a5d31c08514791e9f6e921e69ace539f60051e757704
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=2.11.0'
    - r-rcolorbrewer
  run:
    - 'r-base >=2.11.0'
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SQUADD.html
  license: 'GPL (>=2)'
  summary: 'This package SQUADD is a SQUAD add-on. It permits to generate SQUAD simulation
    matrix, prediction Heat-Map and Correlation Circle from PCA analysis.'
