{% set version="1.24.0" %}
{% set name="AGDEX" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 61773f0da9f54bd5bccf9b3b525c044c25a0db36641e3074f71e9a393415feed
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-gseabase
    - 'r-base >=2.10'
  run:
    - bioconductor-biobase
    - bioconductor-gseabase
    - 'r-base >=2.10'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/AGDEX.html
  license: 'GPL Version 2 or later'
  summary: 'A tool to evaluate agreement of differential expression for cross-species
    genomics'
