{% set version="1.8.0" %}
{% set name="AIMS" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 609a6cbcac06bea1ad4d2109c44ef14f4243f994da3f1d3363391a79d596ca1f
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - 'r-base >=2.10'
    - r-e1071
  run:
    - bioconductor-biobase
    - 'r-base >=2.10'
    - r-e1071
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/AIMS.html
  license: Artistic-2.0
  summary: 'This package contains the AIMS implementation. It contains necessary functions
    to assign the five intrinsic molecular subtypes (Luminal A, Luminal B, Her2-enriched,
    Basal-like, Normal-like). Assignments could be done on individual samples as well
    as on dataset of gene expression data.'
