{% set version="1.6.0" %}
{% set name="SISPA" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 54067c9e31af44521a48653c71457eab94b2f2693e64e5e9ea774436e196db34
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-genefilter
    - bioconductor-gsva
    - 'r-base >=3.2'
    - r-changepoint
    - r-data.table
    - r-ggplot2
    - r-plyr
  run:
    - bioconductor-genefilter
    - bioconductor-gsva
    - 'r-base >=3.2'
    - r-changepoint
    - r-data.table
    - r-ggplot2
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/SISPA.html
  license: GPL-2
  summary: 'Sample Integrated Set Profile Analysis (SISPA) is a method designed to
    define sample groups with similar gene set enrichment profiles.'
