{% set version="1.14.0" %}
{% set name="methylMnM" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 98abe03ed3c5e95456bc50f8dc8a483535fb186ba5da0a62ad66c31687ff1195
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-edger
    - 'r-base >=2.12.1'
    - r-statmod
  run:
    - bioconductor-edger
    - 'r-base >=2.12.1'
    - r-statmod
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/methylMnM.html
  license: GPL-3
  summary: 'To give the exactly p-value and q-value of MeDIP-seq and MRE-seq data
    for different samples comparation.'
