{% set version="1.12.2" %}
{% set name="GenomeInfoDb" %}
{% set bioc="3.5" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: d7658b4916130cfda19d86b4631b0592fcfe60c20adf78c008f7d96c597d5dc2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biocgenerics >=0.13.8'
    - bioconductor-genomeinfodbdata
    - 'bioconductor-iranges >=1.99.26'
    - 'bioconductor-s4vectors >=0.9.25'
    - 'r-base >=3.1'
    - r-rcurl
  run:
    - 'bioconductor-biocgenerics >=0.13.8'
    - bioconductor-genomeinfodbdata
    - 'bioconductor-iranges >=1.99.26'
    - 'bioconductor-s4vectors >=0.9.25'
    - 'r-base >=3.1'
    - r-rcurl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Contains data and functions that define and allow translation between different chromosome sequence naming conventions (e.g., "chr1" versus "1"), including a function that attempts to place sequence names in their natural, rather than lexicographic, order.'
