{% set version="1.12.0" %}
{% set name="Mirsynergy" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'
source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'http://bioconductor.org/packages/3.5/bioc/src/contrib/{{ name }}_{{ version
      }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/{{ name }}/{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 869f2cc4c3fa08f48a43c9607ca29ef5947a277a0e3134b4e01f877cd3081e9c
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-base >=3.0.2'
    - r-ggplot2
    - r-gridextra
    - r-igraph
    - r-matrix
    - r-rcolorbrewer
    - r-reshape
    - r-scales
  run:
    - 'r-base >=3.0.2'
    - r-ggplot2
    - r-gridextra
    - r-igraph
    - r-matrix
    - r-rcolorbrewer
    - r-reshape
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: http://bioconductor.org/packages/3.5/bioc/html/Mirsynergy.html
  license: GPL-2
  summary: 'Detect synergistic miRNA regulatory modules by overlapping neighbourhood
    expansion.'
